### ISSUE TITLE
URI style for E42_Identifiers

### ISSUE THREAD

**Issue by BOberreither** [acdh-oeaw/acdh-cidoc-pyutils#51]
LK texts:

E42_Identifiers' URIs could be built like the other URIs:
Instead of 
<https://sk.acdh.oeaw.ac.at/identifier/D_000079-002-000>
>>
<https://sk.acdh.oeaw.ac.at/D_000079-002-000/identifier/0>
(added number, because there are usually several identifiers ...)

**Comment by csae8092** [comment]
moved to https://github.com/semantic-kraus/lk-data/issues/4
